tag = "webui"
concurrency = 2
workdir = "workdir"
log_path = "log.txt"
download_path = "downloads_folder"
use_local_proxy = false
split = "validation"
save_path = "dra.jsonl"

[google]
api_key = "AIzaSyDcPf4frVf4Avb-ZgiwudDCtGmFWqxWIVM"
model_name = "gemini-2.5-flash"
temperature = 0.1
max_tokens = 1000
timeout = 30

[web_search_tool]
engine = "Google"
fallback_engines = [ "DuckDuckGo",]
retry_delay = 5
max_retries = 2
lang = "en"
country = "us"
filter_year = 0
num_results = 3

[deep_researcher_tool]
model_id = "gemini-2.5-flash"
max_depth = 2
max_insights = 10
time_limit_seconds = 60
max_follow_ups = 2

[deep_analyzer_tool]
analyzer_model_ids = [ "gemini-2.5-flash",]
summarizer_model_id = "gemini-2.5-flash"

[python_interpreter_tool]
model_id = "gemini-2.5-flash"
timeout = 30
max_iterations = 5
result_window_size = 800

[auto_browser_tool]
model_id = "gemini-2.5-flash"
timeout = 30
viewport_width = 1024
viewport_height = 768

[browser_tool]
model_id = "gemini-2.5-flash"
timeout = 30
max_depth = 3

[planning_tool]
model_id = "gemini-2.5-flash"
timeout = 30
max_steps = 10

[browser_use_tool]
model_id = "gemini-2.5-flash"
timeout = 30

[default_agent]
model_id = "gemini-2.5-flash"

[agent]
name = "dra"
use_hierarchical_agent = true

[dataset]
name = "webui_test"
path = "data/test"

[models.gemini-2]
5-flash = "google"

[agent.general_agent_config]
model_id = "gemini-2.5-flash"
name = "general_agent"
description = "A general agent that can perform various tasks and manage other agents."
max_steps = 20
template_path = "src/agent/general_agent/prompts/general_agent.yaml"
tools = [ "python_interpreter",]
mcp_tools = [ "get_weather",]

[agent.planning_agent_config]
model_id = "gemini-2.5-flash"
name = "planning_agent"
description = "A planning agent that can plan the steps to complete the task."
max_steps = 20
template_path = "src/agent/planning_agent/prompts/planning_agent.yaml"
tools = [ "planning",]
managed_agents = [ "deep_analyzer_agent", "browser_use_agent", "deep_researcher_agent",]
mcp_tools = []

[agent.deep_analyzer_agent_config]
model_id = "gemini-2.5-flash"
name = "deep_analyzer_agent"
description = "Performs systematic, step-by-step analysis of a given task."
max_steps = 3
template_path = "src/agent/deep_analyzer_agent/prompts/deep_analyzer_agent.yaml"
tools = [ "deep_analyzer", "python_interpreter",]
mcp_tools = []

[agent.browser_use_agent_config]
model_id = "gemini-2.5-flash"
name = "browser_use_agent"
description = "Searches relevant web pages and interacts with them to find answers."
max_steps = 5
template_path = "src/agent/browser_use_agent/prompts/browser_use_agent.yaml"
tools = [ "auto_browser_use", "python_interpreter",]
mcp_tools = []

[agent.deep_researcher_agent_config]
model_id = "gemini-2.5-flash"
name = "deep_researcher_agent"
description = "Conducts extensive web searches to complete tasks."
max_steps = 3
template_path = "src/agent/deep_researcher_agent/prompts/deep_researcher_agent.yaml"
tools = [ "deep_researcher", "python_interpreter",]
mcp_tools = []
